### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by freephile** [freephile/meza#105]
The comparison of 39.x versus an old Quality Box install shows a degradation in performance.

| Category          | Quality Box | Meza 39.x |
| :---------------- | :---------: | :-------: |
| Performance       |   88        |     83    |
| Accessibility     |   96 |  88 |
| Best Practices |      96  | 96 |
| SEO | 82 | 91 |

https://pagespeed.web.dev/analysis/https-wiki-freephile-org-wiki-Main_Page/qosvaqtrbf?form_factor=mobile

**Comment by freephile** [comment]
## compare 

https://googlechrome.github.io/lighthouse/viewer/?gist=80ccc8332c10d438f9328ecf5355b798 for freephile.org https://wiki.freephile.org/wiki/Features

with https://googlechrome.github.io/lighthouse/viewer/?gist=2d3c57a647dc75aeecddf559bd3a58ea for the 39.x version

**Comment by freephile** [comment]
Speed index dropped from 2.9s to 3.8s

- enable [text compression](https://developer.chrome.com/docs/lighthouse/performance/uses-text-compression/)

**Comment by freephile** [comment]
## Advice from "LightHouse" 
- the performance tool in Chrome DevTools.

Speed index is now 1.9s (score 88) as of 2026/03 but we need it to be 1 second
- [ ] enable text compression (in Apache)
- [ ] [Render blocking requests](https://developer.chrome.com/docs/performance/insights/render-blocking) Est savings of 860 ms
- [ ] [Document request latency](https://developer.chrome.com/docs/performance/insights/document-latency) Est savings of 45 KiB
- [ ] Use efficient [cache lifetimes](https://developer.chrome.com/docs/performance/insights/cache) Est savings of 829 KiB
- [x] [Modern HTTP](https://developer.chrome.com/docs/performance/insights/modern-http) Est savings of 150 ms
- [ ] Font display Est savings of 60 ms - Consider setting [font-display](https://developer.chrome.com/docs/performance/insights/font-display?utm_source=lighthouse&utm_medium=devtools) to swap or optional to ensure text is consistently visible. swap can be further optimized to mitigate layout shifts with [font metric overrides](https://developer.chrome.com/blog/font-fallbacks).

**Comment by freephile** [comment]
## render blockers
- first-party [load.php](https://wiki.freephile.org/wiki/load.php?lang=en&modules=ext.Lingo.styles%7Cext.bootstrap.styles%7Cext.bootstrapComponents.bootstrap.fix%7Cext.cite.styles%7Cext.echo.styles.badge%7Cext.embedVideo.styles%7Cext.pygments%7Cext.relatedArticles.styles%7Cext.srf.styles%7Cext.uls.pt%7Cext.visualEditor.desktopArticleTarget.noscript%7Cext.watchanalytics.base%7Cext.watchanalytics.pagescores.styles%7Coojs-ui.styles.icons-alerts%7Cskins.vector.icons%2Cstyles%7Cskins.vector.search.codex.styles&only=styles&skin=vector-2022)
- [site styles](https://wiki.freephile.org/wiki/load.php?lang=en&modules=site.styles&only=styles&skin=vector-2022)
- from Meta [more menu gadget](https://meta.wikimedia.org/w/index.php?title=MediaWiki:Gadget-MoreMenu-pagestyles.en.css&action=raw&ctype=text/css)

**Comment by freephile** [comment]
- [x] Read [Timo's experience upgrading Wikipedia](https://timotijhof.net/posts/2022/http-2-performance-revisited/) in 2022 with history.
- [x] Test H2 implementation
- [ ] Update [documentation on-wiki](https://wiki.freephile.org/wiki/PHP_Accelerator) since APC is old now - direct to new APCu content
- [ ] Add apcu - because apparently it is missing in current Meza
- [x] Use a Cache-Control header
- [x] Add mod_expires and set appropriate expiry for static content (images / css)
- [ ] Add [ServerInfo](https://github.com/freephile/ServerInfo/) extension (probably needs to be updated)
- [x] Use better tools than "Lighthouse" (from Chrome DevTools) - such as [Browsertime](https://github.com/sitespeedio/browsertime) and WebPageReplay like WMF does for their [Performance/Synthetic testing](https://wikitech.wikimedia.org/wiki/Performance/Synthetic_testing)

Example for Cache-Control
```
   # Initially we cached just json, yaml, csv, and tsv files
   # But we found that mod_autoindex responses were not cached
   # so applying a more thorough cache on anything under /published
   <IfModule mod_headers.c>
     <LocationMatch "/published">
         Header set Cache-Control "max-age=3600, public, must-revalidate"
     </LocationMatch>
   </IfModule>
```


See for example:
- https://gerrit.wikimedia.org/g/operations/docker-images/production-images/+/374d18b0fc6cefb9267a98df520d8d644662185a/images/MediaWiki/httpd/apache2/mods-available/expires.conf
- https://gerrit.wikimedia.org/g/operations/puppet/+/f3da82920b0a7c0f5eaf61f4dc5d5fc9e3ba17f3/modules/mediawiki/files/apache/modules/expires.conf
- https://gerrit.wikimedia.org/g/mediawiki/vagrant/%2B/HEAD/puppet/modules/role/manifests/simple_performant.pp


```apache
# Expires and CORS for static content
# sends max-age and Expires header, time in seconds
<IfModule mod_expires.c>
   ExpiresActive On
   <Directory ~ "^/srv/mediawiki/(images|docroot|static)">
        <FilesMatch "\.(gif|jpe?g|png|css|js|json|woff|woff2|svg|eot|ttf|ico)$">
            ExpiresByType image/gif A31536000
            ExpiresByType image/png A31536000
            ExpiresByType image/jpeg A31536000
            ExpiresByType text/css A31536000
            ExpiresByType text/javascript A31536000
            ExpiresByType application/x-javascript A31536000
            ExpiresByType application/json A31536000
            ExpiresByType application/font-woff A31536000
            ExpiresByType application/font-woff2 A31536000
            ExpiresByType image/svg+xml A31536000
            ExpiresByType image/x-icon A31536000
            ExpiresByType image/vnd.microsoft.icon A31536000
            ExpiresByType application/vnd.ms-fontobject A31536000
            ExpiresByType application/x-font-ttf A31536000
            Header add Access-Control-Allow-Origin "*"
        </FilesMatch>
    </Directory>
</IfModule>
```

**Comment by freephile** [comment]
1.1 second page loads now

https://github.com/user-attachments/assets/d1d489af-df74-45b4-8556-82714723756f

**Comment by freephile** [comment]
`sudo dnf install -y php-pecl-apcu`

**Comment by freephile** [comment]
## Manual
- https://www.mediawiki.org/wiki/Manual:Performance_tuning
- https://www.mediawiki.org/wiki/ResourceLoader/Architecture
- https://www.mediawiki.org/wiki/Manual:Configuration_settings#Cache

**Comment by freephile** [comment]
Still some straglers here, and still need to look at the performance on Mobile.
